# auth variables
nepaltoursim:
  namespace: nepal-tourism
  labels: nt
namespace: nepal-tourism
replicaCount: 1


image:
  repository: siddhartha536/nepal-tourism-frontend  # change to your Docker Hub username
  pullPolicy: IfNotPresent
  tag: "v1.0.1"                            # will be updated by Jenkins

service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Environment variables for the specific microservice
env:
  SERVICE_NAME: "frontend"
  PORT: "80"

# Sensitive data – will be base64-encoded in the secret template
secrets:
  mongoUri: "mongodb+srv://siddhartha:siddhartha@nepal-tourism.dl9evnu.mongodb.net/central-db"   # placeholder
  jwtSecret: "temp_secret"                       

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80